platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5.4'
pod 'AFNetworking-RACExtensions', '~> 0.1.8'
pod 'ReactiveCocoa', '~> 2.5'
pod 'ReactiveViewModel', '~> 0.3'
pod 'Mantle', '~> 2.0.2'
pod 'SDWebImage', '~> 3.7.2'
pod 'Masonry', '~> 0.6.2'
pod 'MBProgressHUD', '~> 0.9.1'
